# Generated by Django 4.1.2 on 2022-10-14 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='projectaffectedperson',
            name='National_id_no',
        ),
        migrations.RemoveField(
            model_name='projectaffectedperson',
            name='crops',
        ),
        migrations.RemoveField(
            model_name='projectaffectedperson',
            name='land',
        ),
        migrations.RemoveField(
            model_name='projectaffectedperson',
            name='location',
        ),
        migrations.AddField(
            model_name='crop',
            name='description',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='price',
            field=models.PositiveIntegerField(default=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='quality',
            field=models.CharField(choices=[('Mature_good', 'Mature_good'), ('Mature', 'Mature'), ('Immature_good', 'Immature_good'), ('Immature', 'Immature')], default=2, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='rating',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='price',
            field=models.PositiveIntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectaffectedperson',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectaffectedperson',
            name='id_no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectaffectedperson',
            name='quantity_of_crops',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectaffectedperson',
            name='type_of_crops',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='api.crop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectaffectedperson',
            name='type_of_land',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='land', to='api.land'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='projectaffectedperson',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='projectaffectedperson',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='projectaffectedperson',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_categories', to='api.crop'),
        ),
        migrations.AddField(
            model_name='projectaffectedperson',
            name='construction_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='construction', to='api.constructionbuilding'),
            preserve_default=False,
        ),
    ]
