# Generated by Django 4.1.2 on 2022-10-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_constructionbuilding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionbuilding',
            name='description',
            field=models.TextField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='land',
            name='description',
            field=models.TextField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='constructionbuilding',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='land',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
