# Generated by Django 4.1.2 on 2022-10-07 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
