# Generated by Django 4.1.2 on 2022-10-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_constructionbuilding_description_land_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='description',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
