# Generated by Django 4.1.2 on 2022-10-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_land_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionbuilding',
            name='description',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
