# Generated by Django 4.1.2 on 2022-10-14 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_crop_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=256)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='projectaffectedperson',
            name='trees',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='api.crop'),
            preserve_default=False,
        ),
    ]
