# Generated by Django 4.1.2 on 2022-10-14 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_alter_projectaffectedperson_trees'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectaffectedperson',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pap', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='projectaffectedperson',
            name='construction_type',
        ),
        migrations.RemoveField(
            model_name='projectaffectedperson',
            name='trees',
        ),
        migrations.RemoveField(
            model_name='projectaffectedperson',
            name='type_of_crops',
        ),
        migrations.RemoveField(
            model_name='projectaffectedperson',
            name='type_of_land',
        ),
        migrations.AddField(
            model_name='projectaffectedperson',
            name='construction_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='construction', to='api.constructionbuilding'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectaffectedperson',
            name='trees',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='api.tree'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectaffectedperson',
            name='type_of_crops',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='api.crop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectaffectedperson',
            name='type_of_land',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='land', to='api.land'),
            preserve_default=False,
        ),
    ]
