# Generated by Django 4.1.2 on 2022-10-15 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_projectaffectedperson_type_of_crops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectaffectedperson',
            name='type_of_crops',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.category'),
        ),
    ]
