# Generated by Django 4.1.2 on 2022-10-15 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_crop_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectaffectedperson',
            name='type_of_land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='api.land'),
        ),
    ]
