# Generated by Django 4.1.2 on 2022-10-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_projectaffectedperson_type_of_land'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='land',
            options={'ordering': ('name',), 'verbose_name': 'land', 'verbose_name_plural': 'land'},
        ),
    ]
