# Generated by Django 4.1.2 on 2022-10-19 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0016_alter_land_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectaffectedperson',
            name='type_of_crops',
        ),
        migrations.AddField(
            model_name='crop',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='pap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_affected_persons', to='api.projectaffectedperson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectaffectedperson',
            name='crops',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=1, max_length=13),
            preserve_default=False,
        ),
    ]
