# Generated by Django 4.1.2 on 2022-10-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_projectaffectedperson_type_of_crops_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectaffectedperson',
            name='crops',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=13),
        ),
    ]
