# Generated by Django 4.1.2 on 2022-10-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_projectaffectedperson_crops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectaffectedperson',
            name='quantity_of_crops',
        ),
        migrations.AddField(
            model_name='crop',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
