# Generated by Django 4.1.2 on 2022-10-25 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0023_crop_created_crop_updated_papland'),
    ]

    operations = [
        migrations.AddField(
            model_name='papland',
            name='pap_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='land_owners', to='api.projectaffectedperson'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='papland',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paplands', to=settings.AUTH_USER_MODEL),
        ),
    ]
