# Generated by Django 4.1.2 on 2022-10-28 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_papland_pap_name_alter_papland_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='pap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pap_crops', to='api.projectaffectedperson'),
        ),
    ]
