# Generated by Django 4.1.2 on 2022-10-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_crop_pap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='papland',
            old_name='pap_name',
            new_name='pap',
        ),
    ]
