# Generated by Django 4.1.2 on 2022-10-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_papland_tenure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='description',
            field=models.TextField(blank=True, default='edible', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crop',
            name='price',
            field=models.PositiveIntegerField(default=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crop',
            name='rating',
            field=models.PositiveIntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='papland',
            name='land_services',
            field=models.TextField(blank=True, default='Agriculture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='papland',
            name='land_use',
            field=models.TextField(blank=True, default='agriculture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='papland',
            name='survey_no',
            field=models.CharField(blank=True, default='umnwer123', max_length=200),
            preserve_default=False,
        ),
    ]
